services:
  postgres:
    image: postgres:16-alpine
    container_name: linkwarden_postgres
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    container_name: linkwarden
    ports:
      - 3210:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
networks: {}
